on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      Configuration: Release
      TreatWarningsAsErrors: true
      WarningsNotAsErrors: 1591
      Deterministic: true
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: dotnet tool install -g GitVersion.Tool --version 5.10.0
      - name: Resolve version
        id: version
        run: |
          dotnet-gitversion > version.json
          version="$(jq -r '.SemVer' version.json)"
          pr_version="$(jq -r '.MajorMinorPatch' version.json)-$(jq -r '.PreReleaseLabel' version.json).${{ github.run_number }}.${{ github.run_attempt }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then version=$pr_version; fi
          echo "Resolved version: $version"
          echo "Version=${version}" >> "$GITHUB_ENV"
      - run: dotnet restore --configfile nuget.config
      - run: dotnet format --no-restore --verify-no-changes --severity info --exclude-diagnostics IDE0270
      - run: dotnet build --no-restore
      - run: dotnet test --no-build
      - run: dotnet pack --no-build
      - uses: actions/upload-artifact@v3
        with:
          name: nuget_packages
          path: src/CommandLine/bin/Release/*.*nupkg
      - uses: actions/upload-artifact@v3
        with:
          name: nuget_packages
          path: src/Common/bin/Release/*nupkg
      - uses: actions/upload-artifact@v3
        with:
          name: nuget_packages
          path: src/FileSystem/bin/Release/*.*nupkg

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref_type == 'tag'
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget_packages
          path: nuget_packages
      - run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        working-directory: nuget_packages
